name: format

on:
  - push
  - pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4

      - run: pip install black djhtml isort

      - name: Format Python code (isort, Black)
        run: |
          isort --profile black . 
          black .
      
      - name: Format Jinja2 templates (DjHTML)
        run: djhtml .
      
      - name: Format everything else (Prettier)
        run: npx prettier . --write

      - name: Commit formatting
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format Python code with Black"
